package render

import (
	"fmt"
	"io"

	"github.com/JaydenCJ/profgate/internal/budget"
	"github.com/JaydenCJ/profgate/internal/diff"
	"github.com/JaydenCJ/profgate/internal/version"
)

// MarkdownDiff renders the diff as GitHub-flavored Markdown, ready to
// paste (or pipe) into a PR comment or a CI job summary.
func MarkdownDiff(w io.Writer, r *diff.Report, o Options) {
	fmt.Fprintf(w, "## profgate diff\n\n")
	mdHeader(w, r)
	rows := visible(r, o)
	if len(rows) == 0 {
		fmt.Fprintf(w, "No per-function changes.\n")
	} else {
		mdMoversTable(w, rows, r.SampleType.Unit)
	}
	mdFooter(w, fmt.Sprintf("%s compared, showing %d", plural(len(r.Entries), "function", "functions"), len(rows)))
}

// MarkdownCheck renders the check verdict as Markdown. The breach table
// comes first so a failing gate leads with the reason, followed by the
// top movers for context.
func MarkdownCheck(w io.Writer, r *diff.Report, res *budget.Result, o Options) {
	if res.Failed() {
		fmt.Fprintf(w, "## profgate check — ❌ FAIL\n\n")
	} else {
		fmt.Fprintf(w, "## profgate check — ✅ PASS\n\n")
	}
	mdHeader(w, r)

	if res.Failed() {
		fmt.Fprintf(w, "### Budget breaches (%d)\n\n", len(res.Violations))
		fmt.Fprintf(w, "| Function | Metric | Base | Head | Δ | Budget | Rule |\n")
		fmt.Fprintf(w, "|---|---|---:|---:|---:|---|---|\n")
		u := r.SampleType.Unit
		for _, v := range res.Violations {
			fmt.Fprintf(w, "| `%s` | %s | %s | %s | **%s** | `%s=%s` | %s |\n",
				v.Function, v.Metric,
				Value(v.Base, u), Value(v.Head, u),
				deltaCell(v.Base, v.Head, u),
				v.Key, v.LimitRaw, ruleRef(v.RuleLine))
		}
		fmt.Fprintln(w)
	} else {
		fmt.Fprintf(w, "%s passed across %s.\n\n",
			plural(res.Checked, "budget check", "budget checks"),
			plural(res.Matched, "matched function", "matched functions"))
	}

	if rows := visible(r, o); len(rows) > 0 {
		fmt.Fprintf(w, "### Top movers\n\n")
		mdMoversTable(w, rows, r.SampleType.Unit)
	}
	mdFooter(w, fmt.Sprintf("%s across %s",
		plural(res.Checked, "budget check", "budget checks"),
		plural(res.Matched, "matched function", "matched functions")))
}

func mdHeader(w io.Writer, r *diff.Report) {
	u := r.SampleType.Unit
	fmt.Fprintf(w, "`%s` → `%s` · sample type `%s`\n\n", r.BaseLabel, r.HeadLabel, r.SampleType)
	fmt.Fprintf(w, "**Total:** %s → %s (**%s**)\n\n",
		Value(r.TotalBase, u), Value(r.TotalHead, u), deltaCell(r.TotalBase, r.TotalHead, u))
}

func mdMoversTable(w io.Writer, rows []diff.Entry, unit string) {
	fmt.Fprintf(w, "| Function | Flat (base) | Flat (head) | Δ Flat | Cum (base) | Cum (head) | Δ Cum |\n")
	fmt.Fprintf(w, "|---|---:|---:|---:|---:|---:|---:|\n")
	for _, e := range rows {
		fmt.Fprintf(w, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			e.Name,
			Value(e.FlatBase, unit), Value(e.FlatHead, unit), deltaCell(e.FlatBase, e.FlatHead, unit),
			Value(e.CumBase, unit), Value(e.CumHead, unit), deltaCell(e.CumBase, e.CumHead, unit))
	}
	fmt.Fprintln(w)
}

func mdFooter(w io.Writer, detail string) {
	fmt.Fprintf(w, "<sub>Generated by [profgate](https://github.com/JaydenCJ/profgate) v%s · %s.</sub>\n",
		version.Version, detail)
}
